volumes:
  data:
  db:
  redis:

services:
  dfu-wiki:
    image: docmost-test:latest
    container_name: wiki
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}"
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - data:/app/data/storage

  db:
    image: postgres:16-alpine
    container_name: wiki-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: wiki-redis  # FIXED typo: =redis → -redis
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data